name: Build Linuxloops Live Disk
on:
  push:
    branches:
      - 'main'
    paths:
      - 'linuxloops'
      - '.github/workflows/live.yml'
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-live-disk:
    name: Build Linuxloops Live Disk
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout linuxloops script
        uses: actions/checkout@v3
      - name: Set current date
        run: echo "current_date=$(date '+%Y%m%d')" >> $GITHUB_ENV
      - name: Build Linuxloops Live Disk
        run: sudo bash linuxloops -distro Debian -env cinnamon -dst linuxloops_live_${{ env.current_date }}.img -u -b -c "firefox-esr gedit gparted evince"
      - name: Compress Linuxloops Live Disk
        run: 7z a linuxloops_live_${{ env.current_date }}.7z linuxloops_live_${{ env.current_date }}.img
      - name: Generate release details
        run: |
          RELEASE_FILE=linuxloops_live_${{ env.current_date }}.7z
          RELEASE_VERSION=$(echo "$RELEASE_FILE" | cut -d'.' -f1 | cut -d'_' -f2)
          RELEASE_DATE=$(echo "$RELEASE_FILE" | cut -d'.' -f1 | cut -d'_' -f3)
          echo "Found linuxloops release: ${RELEASE_FILE} with version ${RELEASE_VERSION} and date ${RELEASE_DATE}"
          echo "RELEASE_FILE=${RELEASE_FILE}" >> $GITHUB_ENV
          echo "RELEASE_TAG=linuxloops-${RELEASE_VERSION}-${RELEASE_DATE}" >> $GITHUB_ENV
          echo "RELEASE_NAME=Linuxloops ${RELEASE_VERSION} ${RELEASE_DATE}" >> $GITHUB_ENV          
      - name: Create a release and upload artifacts as assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.RELEASE_FILE }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          tag: "${{ env.RELEASE_TAG }}"
          name: "${{ env.RELEASE_NAME }}"
          commit: "${{ github.ref_name }}"
          body: "${{ github.event.head_commit.message }}"
